### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by chandu0101** [chandu0101/sri-reactive2015#1]
# Schedule
- [x] fix name display
- [x] add triangles in tab highlight
# Speakers
- [ ] modal for speaker info
